import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting YogyaSetu database seed...');

  // Clear existing records if needed (in safe order)
  await prisma.notification.deleteMany({});
  await prisma.applicationTracker.deleteMany({});
  await prisma.bookmark.deleteMany({});
  await prisma.scheme.deleteMany({});
  await prisma.category.deleteMany({});
  await prisma.user.deleteMany({});

  // 1. Create Default Admin & Citizen Users
  const adminPasswordHash = await bcrypt.hash('Admin@12345', 10);
  const userPasswordHash = await bcrypt.hash('User@12345', 10);

  const admin = await prisma.user.create({
    data: {
      name: 'YogyaSetu Super Admin',
      email: 'admin@yogyasetu.gov.in',
      mobile: '9876543210',
      passwordHash: adminPasswordHash,
      role: 'ADMIN',
      state: 'Delhi',
      gender: 'Male',
      age: 38,
      occupation: 'Government Officer',
      income: 1200000,
      category: 'General',
      education: 'Post Graduate',
      isActive: true,
    },
  });

  const demoUser = await prisma.user.create({
    data: {
      name: 'Rahul Sharma',
      email: 'rahul.sharma@example.com',
      mobile: '9123456780',
      passwordHash: userPasswordHash,
      role: 'USER',
      state: 'Uttar Pradesh',
      gender: 'Male',
      age: 24,
      occupation: 'Student',
      income: 180000,
      category: 'OBC',
      education: 'Graduate',
      isActive: true,
    },
  });

  console.log('✅ Created Admin and Demo User accounts');

  // 2. Create Categories
  const categoriesData = [
    {
      nameEn: 'Students & Youth',
      nameHi: 'छात्र एवं युवा',
      slug: 'students',
      icon: 'GraduationCap',
      descriptionEn: 'Scholarships, coaching assistance, and education loan subsidies for school and university students.',
      descriptionHi: 'छात्रवृत्ति, कोचिंग सहायता और स्कूल-कॉलेज छात्रों के लिए शिक्षा ऋण सब्सिडी।',
    },
    {
      nameEn: 'Farmers & Agriculture',
      nameHi: 'किसान एवं कृषि',
      slug: 'farmers',
      icon: 'Sprout',
      descriptionEn: 'Direct income support, crop insurance, irrigation, and institutional credit for cultivators.',
      descriptionHi: 'प्रत्यक्ष आय सहायता, फसल बीमा, सिंचाई और किसानों के लिए संस्थागत ऋण।',
    },
    {
      nameEn: 'Women & Child',
      nameHi: 'महिला एवं बाल विकास',
      slug: 'women',
      icon: 'HeartHandshake',
      descriptionEn: 'Maternity assistance, girl child protection, entrepreneurship grants, and social welfare.',
      descriptionHi: 'मातृत्व सहायता, बालिका संरक्षण, महिला उद्यमिता अनुदान एवं सामाजिक कल्याण।',
    },
    {
      nameEn: 'Senior Citizens',
      nameHi: 'वरिष्ठ नागरिक',
      slug: 'senior-citizens',
      icon: 'Award',
      descriptionEn: 'Old age pensions, assisted living devices, and guaranteed pension security schemes.',
      descriptionHi: 'वृद्धावस्था पेंशन, सहायक जीवन उपकरण एवं सुनिश्चित पेंशन सुरक्षा योजनाएं।',
    },
    {
      nameEn: 'Persons with Disabilities',
      nameHi: 'दिव्यांगजन',
      slug: 'divyangjan',
      icon: 'Accessibility',
      descriptionEn: 'Aids and assistive devices, disability pensions, education scholarships, and rehabilitation.',
      descriptionHi: 'सहायक उपकरण, दिव्यांगता पेंशन, विशेष छात्रवृत्तियां एवं पुनर्वास योजनाएं।',
    },
    {
      nameEn: 'Employment & Skills',
      nameHi: 'रोजगार एवं कौशल',
      slug: 'employment',
      icon: 'Briefcase',
      descriptionEn: 'Guaranteed wage employment, skill development training, and micro-enterprise loans.',
      descriptionHi: 'गारंटीकृत मजदूरी रोजगार, कौशल विकास प्रशिक्षण और सूक्ष्म-उद्यम ऋण।',
    },
    {
      nameEn: 'Housing & Shelter',
      nameHi: 'आवास एवं आश्रय',
      slug: 'housing',
      icon: 'Home',
      descriptionEn: 'Affordable pucca housing subsidies for urban and rural economically weaker families.',
      descriptionHi: 'शहरी और ग्रामीण आर्थिक रूप से कमजोर परिवारों के लिए पक्के मकान हेतु सब्सिडी।',
    },
    {
      nameEn: 'Health & Wellness',
      nameHi: 'स्वास्थ्य एवं परिवार कल्याण',
      slug: 'health',
      icon: 'HeartPulse',
      descriptionEn: 'Cashless secondary and tertiary hospitalization cover, affordable generic medicines, and immunizations.',
      descriptionHi: 'निशुल्क द्वितीयक व तृतीयक अस्पताल भर्ती कवर, सस्ती जेनेरिक दवाएं और सार्वभौमिक टीकाकरण।',
    },
  ];

  const categoriesMap: Record<string, string> = {};
  for (const cat of categoriesData) {
    const created = await prisma.category.create({ data: cat });
    categoriesMap[cat.slug] = created.id;
  }
  console.log('✅ Created 8 Master Categories');

  // 3. Create Authentic Schemes
  const schemesData = [
    // STUDENTS
    {
      categoryId: categoriesMap['students'],
      titleEn: 'Central Sector Scheme of Scholarships for College and University Students',
      titleHi: 'कॉलेज और विश्वविद्यालय के छात्रों के लिए केंद्रीय क्षेत्र छात्रवृत्ति योजना',
      descriptionEn: 'Provides financial assistance to meritorious students from low-income families to meet part of their daily expenses while pursuing higher education.',
      descriptionHi: 'उच्च शिक्षा प्राप्त करने वाले निम्न आय वर्ग के मेधावी छात्रों को उनके दैनिक खर्चों को पूरा करने के लिए वित्तीय सहायता प्रदान करता है।',
      benefitsEn: '₹12,000 per annum for undergraduate studies (first 3 years) and ₹20,000 per annum for post-graduate studies directly credited to the student bank account.',
      benefitsHi: 'स्नातक स्तर की पढ़ाई के लिए ₹12,000 प्रति वर्ष (प्रथम 3 वर्ष) और स्नातकोत्तर अध्ययन के लिए ₹20,000 प्रति वर्ष सीधे बैंक खाते में।',
      benefitType: 'Educational',
      benefitAmount: '₹12,000 - ₹20,000 / Year',
      eligibilityJson: JSON.stringify({
        minAge: 17,
        maxAge: 25,
        gender: 'All',
        maxIncome: 450000,
        states: ['All'],
        occupations: ['Student'],
        categories: ['All', 'General', 'OBC', 'SC', 'ST', 'EWS'],
        education: ['12th Pass', 'Graduate'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card of the Student',
        'Class 12th Marksheet (Above 80th percentile)',
        'Annual Family Income Certificate (Below ₹4.5 Lakh)',
        'Bank Account Passbook (Aadhaar linked)',
        'College / University Bonafide Certificate',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Register on NSP', titleHi: 'एनएसपी पर पंजीकरण', descEn: 'Register on National Scholarship Portal (scholarships.gov.in) with Aadhaar and mobile number.', descHi: 'आधार और मोबाइल नंबर के साथ राष्ट्रीय छात्रवृत्ति पोर्टल पर पंजीकरण करें।' },
        { step: 2, titleEn: 'Fill Application', titleHi: 'आवेदन भरें', descEn: 'Fill personal, academic, and bank details, and select Higher Education Scholarship.', descHi: 'व्यक्तिगत, शैक्षणिक और बैंक विवरण भरें।' },
        { step: 3, titleEn: 'Upload Documents', titleHi: 'दस्तावेज अपलोड करें', descEn: 'Upload income certificate and 12th board marksheet.', descHi: 'आय प्रमाण पत्र और 12वीं की अंकतालिका अपलोड करें।' },
        { step: 4, titleEn: 'Institute Verification', titleHi: 'संस्थान सत्यापन', descEn: 'Submit hard copy to your university/college nodal officer for verification.', descHi: 'सत्यापन के लिए अपने कॉलेज/विश्वविद्यालय नोडल अधिकारी को प्रति जमा करें।' },
      ]),
      officialLink: 'https://scholarships.gov.in',
      departmentEn: 'Department of Higher Education, Ministry of Education',
      departmentHi: 'उच्च शिक्षा विभाग, शिक्षा मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['students'],
      titleEn: 'PM YASASVI Scheme for OBC, EBC and DNT Students',
      titleHi: 'पीएम यशस्वी छात्रवृत्ति योजना (ओबीसी, ईबीसी और डीएनटी छात्र)',
      descriptionEn: 'Scholarship scheme for meritorious students belonging to Other Backward Classes (OBC), Economically Backward Classes (EBC), and De-Notified Tribes (DNT) studying in top identified schools.',
      descriptionHi: 'ओबीसी, ईबीसी और डीएनटी वर्ग के शीर्ष चिन्हित विद्यालयों में अध्ययनरत मेधावी छात्रों के लिए छात्रवृत्ति योजना।',
      benefitsEn: '₹75,000 per annum for Class 9 and 10 students; ₹1,25,000 per annum for Class 11 and 12 students covering school tuition fees and hostel charges.',
      benefitsHi: 'कक्षा 9 और 10 के लिए ₹75,000 प्रति वर्ष; कक्षा 11 और 12 के छात्रों के लिए ₹1,25,000 प्रति वर्ष ट्यूशन फीस व छात्रावास शुल्क हेतु।',
      benefitType: 'Educational',
      benefitAmount: 'Up to ₹1,25,000 / Year',
      eligibilityJson: JSON.stringify({
        minAge: 13,
        maxAge: 19,
        gender: 'All',
        maxIncome: 250000,
        states: ['All'],
        occupations: ['Student'],
        categories: ['OBC', 'EBC', 'DNT'],
        education: ['Below 10th', '10th Pass'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card',
        'Caste / Community Certificate (OBC / EBC / DNT)',
        'Income Certificate (Below ₹2.50 Lakh p.a.)',
        'Previous Academic Year Marksheet (Minimum 60%)',
        'Bonafide Student Certificate from Top School',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Check Top Class School List', titleHi: 'स्कूल सूची देखें', descEn: 'Ensure your institution is on the official Ministry of Social Justice identified list.', descHi: 'जांचें कि आपका स्कूल आधिकारिक अनुमोदित सूची में है।' },
        { step: 2, titleEn: 'Apply via NSP Portal', titleHi: 'एनएसपी पोर्टल पर आवेदन', descEn: 'Apply online under Department of Social Justice on National Scholarship Portal.', descHi: 'सामाजिक न्याय विभाग के तहत ऑनलाइन आवेदन करें।' },
        { step: 3, titleEn: 'State / School Verification', titleHi: 'सत्यापन', descEn: 'School and District Welfare Officer verify the application.', descHi: 'स्कूल और जिला कल्याण अधिकारी द्वारा सत्यापन।' },
      ]),
      officialLink: 'https://yet.nta.ac.in',
      departmentEn: 'Ministry of Social Justice and Empowerment',
      departmentHi: 'सामाजिक न्याय एवं अधिकारिता मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['students'],
      titleEn: 'AICTE Pragati Scholarship Scheme for Girl Students',
      titleHi: 'बालिकाओं के लिए एआईसीटीई प्रगति छात्रवृत्ति योजना',
      descriptionEn: 'Scholarship scheme to empower young women pursuing technical education (Degree or Diploma courses) in AICTE-approved institutions.',
      descriptionHi: 'एआईसीटीई द्वारा अनुमोदित संस्थानों में तकनीकी शिक्षा (डिग्री या डिप्लोमा) प्राप्त करने वाली छात्राओं के लिए विशेष योजना।',
      benefitsEn: '₹50,000 per annum towards payment of college fee, computer purchase, books, and stationeries for up to 4 years of study.',
      benefitsHi: 'कॉलेज शुल्क, लैपटॉप/कंप्यूटर खरीद, पुस्तकों और स्टेशनरी के लिए प्रति वर्ष ₹50,000 (अधिकतम 4 वर्षों तक)।',
      benefitType: 'Educational',
      benefitAmount: '₹50,000 / Year',
      eligibilityJson: JSON.stringify({
        minAge: 17,
        maxAge: 25,
        gender: 'Female',
        maxIncome: 800000,
        states: ['All'],
        occupations: ['Student'],
        categories: ['All', 'General', 'OBC', 'SC', 'ST', 'EWS'],
        education: ['12th Pass', 'ITI/Diploma', 'Graduate'],
      }),
      documentsRequired: JSON.stringify([
        'Admission letter to AICTE approved Degree/Diploma program',
        'Class 10th and 12th Marksheets',
        'Annual Family Income Certificate (below ₹8 Lakh)',
        'Aadhaar linked Bank Account details',
        'Declaration from Parents regarding number of girl children',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Enroll in AICTE Course', titleHi: 'पाठ्यक्रम में प्रवेश', descEn: 'Admit into 1st year of technical Degree/Diploma course via centralized admission process.', descHi: 'प्रथम वर्ष के तकनीकी डिग्री/डिप्लोमा में दाखिला लें।' },
        { step: 2, titleEn: 'Online Application', titleHi: 'ऑनलाइन आवेदन', descEn: 'Apply through the National Scholarship Portal under AICTE section.', descHi: 'राष्ट्रीय छात्रवृत्ति पोर्टल के एआईसीटीई सेक्शन में आवेदन करें।' },
      ]),
      officialLink: 'https://www.aicte-india.org/schemes/students-development-schemes/Pragati',
      departmentEn: 'All India Council for Technical Education (AICTE)',
      departmentHi: 'अखिल भारतीय तकनीकी शिक्षा परिषद (एआईसीटीई)',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },

    // FARMERS
    {
      categoryId: categoriesMap['farmers'],
      titleEn: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
      titleHi: 'प्रधानमंत्री किसान सम्मान निधि (पीएम-किसान)',
      descriptionEn: 'Direct income support scheme providing ₹6,000 per year to all landholding farmer families across the country to assist with agricultural and domestic needs.',
      descriptionHi: 'कृषि एवं घरेलू आवश्यकताओं की पूर्ति हेतु देश भर के सभी भूमिधारक किसान परिवारों को प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता।',
      benefitsEn: '₹6,000 per annum paid in three equal installments of ₹2,000 directly transferred into Aadhaar-seeded bank accounts (DBT) every 4 months.',
      benefitsHi: 'हर 4 महीने में ₹2,000 की तीन समान किस्तों में ₹6,000 प्रति वर्ष सीधे आधार से जुड़े बैंक खातों (डीबीटी) में हस्तांतरित।',
      benefitType: 'Financial',
      benefitAmount: '₹6,000 / Year (DBT)',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 75,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Farmer', 'Agricultural Worker'],
        categories: ['All', 'General', 'OBC', 'SC', 'ST', 'EWS'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card (Mandatory for eKYC)',
        'Land Ownership Record (Khatauni / Land Patta)',
        'Active Bank Account linked with Aadhaar & NPCI',
        'Mobile Number linked to Aadhaar for OTP verification',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Visit PM-KISAN Portal', titleHi: 'पीएम-किसान पोर्टल पर जाएं', descEn: 'Visit pmkisan.gov.in and click on "New Farmer Registration".', descHi: 'pmkisan.gov.in पर जाएं और "New Farmer Registration" पर क्लिक करें।' },
        { step: 2, titleEn: 'Enter Aadhaar & State', titleHi: 'आधार व राज्य दर्ज करें', descEn: 'Select Rural or Urban Farmer registration, enter Aadhaar, and verify OTP.', descHi: 'ग्रामीण या शहरी किसान चुनें, आधार दर्ज करें और ओटीपी सत्यापित करें।' },
        { step: 3, titleEn: 'Fill Land Records', titleHi: 'जमीन का विवरण भरें', descEn: 'Enter Khata/Khasra number, land holding size, and upload land deed/passbook.', descHi: 'खसरा/खाता संख्या और भूमि विवरण भरें।' },
        { step: 4, titleEn: 'State Approval & eKYC', titleHi: 'सत्यापन व ई-केवाईसी', descEn: 'Complete mandatory face/biometric or OTP eKYC for installment release.', descHi: 'किस्त जारी होने के लिए अनिवार्य ई-केवाईसी पूरा करें।' },
      ]),
      officialLink: 'https://pmkisan.gov.in',
      departmentEn: 'Department of Agriculture and Farmers Welfare',
      departmentHi: 'कृषि एवं किसान कल्याण विभाग',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['farmers'],
      titleEn: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
      titleHi: 'प्रधानमंत्री फसल बीमा योजना (पीएमएफबीवाई)',
      descriptionEn: 'Provides comprehensive insurance coverage against failure of crops from pre-sowing to post-harvest due to non-preventable natural risks, pests, and diseases.',
      descriptionHi: 'प्राकृतिक आपदाओं, कीटों और रोगों के कारण बुवाई से पूर्व से लेकर कटाई के बाद तक फसल नुकसान के खिलाफ व्यापक बीमा सुरक्षा।',
      benefitsEn: 'Extremely low premium: Only 2% for Kharif crops, 1.5% for Rabi food/oilseeds crops, and 5% for commercial/horticultural crops. Government pays the remaining subsidy.',
      benefitsHi: 'अत्यंत कम प्रीमियम: खरीफ फसलों के लिए मात्र 2%, रबी फसलों के लिए 1.5% और वाणिज्यिक/बागवानी फसलों के लिए 5%। शेष प्रीमियम सरकार देती है।',
      benefitType: 'Financial',
      benefitAmount: 'Full Crop Loss Compensation',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 70,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Farmer', 'Agricultural Worker'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card',
        'Land Possession Certificate / Record of Rights (RoR)',
        'Sowing Certificate issued by Patwari / Village Agriculture Officer',
        'Bank Passbook photocopy (IFSC & Account number)',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Online Enrollment', titleHi: 'ऑनलाइन पंजीकरण', descEn: 'Apply through pmfby.gov.in or via your bank branch / Common Service Centre (CSC).', descHi: 'pmfby.gov.in पर या अपने बैंक/सीएससी केंद्र के माध्यम से आवेदन करें।' },
        { step: 2, titleEn: 'Select Crop & Season', titleHi: 'फसल व मौसम चयन', descEn: 'Select notified crop, survey number, and pay the nominal farmer premium.', descHi: 'अधिसूचित फसल व सर्वे नंबर चुनें और नाममात्र प्रीमियम का भुगतान करें।' },
        { step: 3, titleEn: 'Claim Settlement', titleHi: 'दावा निपटान', descEn: 'In case of localized disaster, report loss within 72 hours via Crop Insurance App.', descHi: 'फसल नुकसान होने पर 72 घंटे के भीतर ऐप या टोल-फ्री नंबर पर सूचना दें।' },
      ]),
      officialLink: 'https://pmfby.gov.in',
      departmentEn: 'Ministry of Agriculture and Farmers Welfare',
      departmentHi: 'कृषि एवं किसान कल्याण मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['farmers'],
      titleEn: 'Kisan Credit Card (KCC) Scheme',
      titleHi: 'किसान क्रेडिट कार्ड (केसीसी) योजना',
      descriptionEn: 'Provides timely and adequate credit to farmers to meet their cultivation and agricultural contingency expenses with interest subvention.',
      descriptionHi: 'किसानों को उनकी खेती, बीज, खाद व आकस्मिक कृषि खर्चों को पूरा करने के लिए ब्याज छूट के साथ रियायती संस्थागत ऋण।',
      benefitsEn: 'Concessional short-term loans up to ₹3 Lakh at an effective interest rate of just 4% per annum (with 3% prompt repayment incentive). Collateral-free loan up to ₹1.6 Lakh.',
      benefitsHi: 'समय पर भुगतान करने पर मात्र 4% वार्षिक ब्याज दर पर ₹3 लाख तक का अल्पकालिक कृषि ऋण। ₹1.6 लाख तक बिना किसी बंधक (कोलैटरल) के ऋण।',
      benefitType: 'Financial',
      benefitAmount: 'Up to ₹3,00,000 Credit at 4% Interest',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 75,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Farmer', 'Agricultural Worker'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Duly filled KCC application form',
        'Identity & Address Proof (Aadhaar Card / Voter ID)',
        'Land holding and crop cultivation documents verified by Revenue Authority',
        'No Dues Certificate from adjacent lending institutions',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Download Form', titleHi: 'फॉर्म डाउनलोड करें', descEn: 'Download KCC application from pmkisan.gov.in or collect from your nearest rural/commercial bank.', descHi: 'आधिकारिक पोर्टल से एक पेज का केसीसी फॉर्म प्राप्त करें।' },
        { step: 2, titleEn: 'Submit at Bank', titleHi: 'बैंक में जमा करें', descEn: 'Submit documents at bank; banks are mandated to process KCC within 14 days.', descHi: 'बैंक में जमा करें, बैंक 14 दिनों के भीतर कार्ड जारी करने के लिए बाध्य हैं।' },
      ]),
      officialLink: 'https://myscheme.gov.in/schemes/kcc',
      departmentEn: 'Ministry of Finance & Ministry of Agriculture',
      departmentHi: 'वित्त मंत्रालय एवं कृषि मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },

    // WOMEN
    {
      categoryId: categoriesMap['women'],
      titleEn: 'Sukanya Samriddhi Yojana (SSY)',
      titleHi: 'सुकन्या समृद्धि योजना (एसएसवाई)',
      descriptionEn: 'A high-interest government savings scheme under the Beti Bachao Beti Padhao campaign to secure the higher education and marriage expenses of girl children.',
      descriptionHi: 'बेटी बचाओ बेटी पढ़ाओ अभियान के तहत बालिकाओं की उच्च शिक्षा और विवाह खर्च को सुरक्षित करने हेतु उच्च ब्याज वाली सरकारी बचत योजना।',
      benefitsEn: 'Current interest rate of 8.2% p.a. (compounded annually), Triple EEE tax exemption under Section 80C, partial withdrawal allowed for higher education after age 18.',
      benefitsHi: 'वर्तमान 8.2% वार्षिक ब्याज दर, आयकर धारा 80C के तहत पूर्ण कर छूट, 18 वर्ष की आयु के बाद उच्च शिक्षा हेतु 50% निकासी की सुविधा।',
      benefitType: 'Financial',
      benefitAmount: '8.2% Guaranteed Interest + Tax Free Returns',
      eligibilityJson: JSON.stringify({
        minAge: 0,
        maxAge: 10,
        gender: 'Female',
        maxIncome: null,
        states: ['All'],
        occupations: ['All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Birth Certificate of the Girl Child',
        'Identity & Address Proof of the Parent / Legal Guardian (Aadhaar / PAN)',
        'Passport sized photographs of girl child and guardian',
        'Initial deposit receipt (minimum ₹250)',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Visit Post Office or Bank', titleHi: 'डाकघर या बैंक जाएं', descEn: 'Visit any India Post office or designated public/private bank branch.', descHi: 'किसी भी डाकघर या अधिकृत बैंक शाखा में जाएं।' },
        { step: 2, titleEn: 'Submit SSY Account Form', titleHi: 'आवेदन फॉर्म जमा करें', descEn: 'Fill Form-1 and submit with child birth certificate and KYC documents.', descHi: 'फॉर्म भरें और बालिका के जन्म प्रमाण पत्र व केवाईसी के साथ जमा करें।' },
        { step: 3, titleEn: 'Collect Passbook', titleHi: 'पासबुक प्राप्त करें', descEn: 'Receive the physical passbook; deposits can be made online via IPPB.', descHi: 'पासबुक प्राप्त करें, बाद में ऑनलाइन जमा भी कर सकते हैं।' },
      ]),
      officialLink: 'https://www.indiapost.gov.in/Financial/pages/content/sukanya-samriddhi-account.aspx',
      departmentEn: 'Department of Posts, Ministry of Communications & Ministry of Finance',
      departmentHi: 'डाक विभाग, संचार एवं वित्त मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['women'],
      titleEn: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
      titleHi: 'प्रधानमंत्री मातृ वंदना योजना (पीएमएमवीवाई)',
      descriptionEn: 'Maternity benefit program providing direct cash incentives to pregnant and lactating mothers for wage loss compensation and nutritional support.',
      descriptionHi: 'गर्भवती महिलाओं और स्तनपान कराने वाली माताओं को मजदूरी के नुकसान की भरपाई और पोषण सुधार के लिए प्रत्यक्ष नकद प्रोत्साहन।',
      benefitsEn: 'Cash incentive of ₹5,000 in two installments for the first child, and an enhanced ₹6,000 in a single installment for a second girl child directly credited via DBT.',
      benefitsHi: 'पहले बच्चे के लिए ₹5,000 दो किस्तों में, तथा दूसरी संतान बालिका होने पर ₹6,000 की प्रोत्साहन राशि सीधे बैंक खाते में।',
      benefitType: 'Financial',
      benefitAmount: '₹5,000 - ₹6,000 Cash Support',
      eligibilityJson: JSON.stringify({
        minAge: 19,
        maxAge: 45,
        gender: 'Female',
        maxIncome: 800000,
        states: ['All'],
        occupations: ['All', 'Daily Wage', 'Homemaker', 'Self-Employed'],
        categories: ['All', 'General', 'OBC', 'SC', 'ST', 'EWS'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Mother and Father Aadhaar Card',
        'Mother Child Protection (MCP) Card / RCH ID',
        'Bank Account linked to Aadhaar (Single account in mother name)',
        'Eligibility proof (e.g. e-Shram card, MNREGA job card, or income below ₹8 Lakh)',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Registration at Anganwadi', titleHi: 'आंगनवाड़ी में पंजीकरण', descEn: 'Register pregnancy at local Anganwadi Centre (AWC) or approved health facility within 570 days.', descHi: 'गर्भावस्था का पंजीकरण नजदीकी आंगनवाड़ी केंद्र में कराएं।' },
        { step: 2, titleEn: 'Online Application (PMMVY Portal)', titleHi: 'ऑनलाइन आवेदन', descEn: 'Beneficiary or Anganwadi worker enters details on pmmvy.wcd.gov.in portal.', descHi: 'pmmvy.wcd.gov.in पर विवरण दर्ज करें।' },
      ]),
      officialLink: 'https://pmmvy.wcd.gov.in',
      departmentEn: 'Ministry of Women and Child Development',
      departmentHi: 'महिला एवं बाल विकास मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['women'],
      titleEn: 'Mahila Samman Savings Certificate (MSSC)',
      titleHi: 'महिला सम्मान बचत प्रमाण पत्र',
      descriptionEn: 'A sovereign small-savings scheme dedicated exclusively to women and girls offering attractive fixed returns for a tenure of two years.',
      descriptionHi: 'महिलाओं और बालिकाओं के लिए विशेष रूप से समर्पित दो वर्ष की आकर्षक ब्याज वाली सरकारी लघु बचत योजना।',
      benefitsEn: 'Guaranteed 7.5% per annum interest compounded quarterly. Deposit limit from ₹1,000 up to ₹2,00,000. Partial withdrawal of up to 40% allowed after 1 year.',
      benefitsHi: '7.5% प्रति वर्ष त्रैमासिक चक्रवृद्धि ब्याज दर। ₹1,000 से लेकर अधिकतम ₹2,00,000 तक जमा। 1 वर्ष बाद 40% तक निकासी की सुविधा।',
      benefitType: 'Financial',
      benefitAmount: '7.5% Fixed Interest (Up to ₹2 Lakh)',
      eligibilityJson: JSON.stringify({
        minAge: 1,
        maxAge: 100,
        gender: 'Female',
        maxIncome: null,
        states: ['All'],
        occupations: ['All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Identity Proof (Aadhaar Card / Voter ID of the woman/guardian)',
        'Address Proof',
        'PAN Card (Mandatory for deposits above ₹50,000)',
        'Account Opening Form (Form-1)',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Visit Post Office or Public Bank', titleHi: 'डाकघर या बैंक जाएं', descEn: 'Available at all Department of Posts post offices and authorized commercial banks.', descHi: 'सभी डाकघरों और अधिकृत बैंकों में उपलब्ध।' },
        { step: 2, titleEn: 'Submit Application & Funds', titleHi: 'आवेदन और राशि जमा करें', descEn: 'Submit KYC and deposit the desired amount in multiples of ₹100.', descHi: 'केवाईसी और जमा राशि जमा करके प्रमाण पत्र प्राप्त करें।' },
      ]),
      officialLink: 'https://myscheme.gov.in/schemes/mssc',
      departmentEn: 'Department of Economic Affairs, Ministry of Finance',
      departmentHi: 'आर्थिक कार्य विभाग, वित्त मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },

    // SENIOR CITIZENS
    {
      categoryId: categoriesMap['senior-citizens'],
      titleEn: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
      titleHi: 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना',
      descriptionEn: 'Monthly social security pension for impoverished senior citizens living below the poverty line across India under National Social Assistance Programme (NSAP).',
      descriptionHi: 'राष्ट्रीय सामाजिक सहायता कार्यक्रम के तहत भारत भर में गरीबी रेखा से नीचे जीवन यापन करने वाले वरिष्ठ नागरिकों के लिए मासिक पेंशन।',
      benefitsEn: 'Monthly pension directly transferred to beneficiary bank account: ₹200-₹500 central component plus state top-up (total ₹1,000 - ₹3,000/month depending on state).',
      benefitsHi: 'मासिक पेंशन सीधे खाते में: केंद्र और राज्य अंश मिलाकर ₹1,000 से ₹3,000 प्रति माह (राज्यवार)।',
      benefitType: 'Social Security',
      benefitAmount: '₹1,000 - ₹3,000 / Month',
      eligibilityJson: JSON.stringify({
        minAge: 60,
        maxAge: 110,
        gender: 'All',
        maxIncome: 100000,
        states: ['All'],
        occupations: ['Senior Citizen', 'Unemployed', 'All'],
        categories: ['All', 'General', 'OBC', 'SC', 'ST', 'EWS'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card / Voter ID for Age Proof (60+ years)',
        'BPL Ration Card / SECC Data Verification',
        'Income Certificate issued by Revenue Officer',
        'Bank Passbook / Post Office Savings Account',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Submit Application Online/Offline', titleHi: 'आवेदन पत्र जमा करें', descEn: 'Apply online on nsap.nic.in or submit form to Gram Panchayat / Block Development Officer (BDO).', descHi: 'nsap.nic.in पर ऑनलाइन या ग्राम पंचायत/बीडीओ कार्यालय में आवेदन जमा करें।' },
        { step: 2, titleEn: 'Social Audit & Verification', titleHi: 'सत्यापन', descEn: 'Local verification of BPL status and age criteria by Social Welfare department.', descHi: 'समाज कल्याण विभाग द्वारा आयु और बीपीएल स्थिति का सत्यापन।' },
      ]),
      officialLink: 'https://nsap.nic.in',
      departmentEn: 'Ministry of Rural Development',
      departmentHi: 'ग्रामीण विकास मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['senior-citizens'],
      titleEn: 'Rashtriya Vayoshri Yojana (RVY)',
      titleHi: 'राष्ट्रीय वयोश्री योजना (आरवीवाई)',
      descriptionEn: 'Provides physical aids and assisted-living devices for senior citizens belonging to BPL category suffering from age-related disabilities or infirmities.',
      descriptionHi: 'आयु संबंधी दुर्बलताओं या दिव्यांगता से पीड़ित बीपीएल वर्ग के वरिष्ठ नागरिकों को निशुल्क सहायक जीवन उपकरण उपलब्ध कराना।',
      benefitsEn: 'Free high-quality assistive equipment: Wheelchairs, walking sticks, hearing aids, crutches, tripod stands, artificial dentures, and spectacles based on medical camp assessment.',
      benefitsHi: 'निशुल्क सहायक उपकरण: व्हीलचेयर, वॉकिंग स्टिक, श्रवण यंत्र (हियरिंग एड), चश्मे, कृत्रिम दांत और तिपाई स्टैंड।',
      benefitType: 'Health',
      benefitAmount: '100% Free Assistive Devices',
      eligibilityJson: JSON.stringify({
        minAge: 60,
        maxAge: 105,
        gender: 'All',
        maxIncome: 180000,
        states: ['All'],
        occupations: ['Senior Citizen', 'All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Proof of Age (Aadhaar / Voter ID / Pension Order)',
        'Proof of BPL Status / Monthly Income below ₹15,000',
        'Medical Certificate of disability/infirmity from Government Doctor',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Attend ALIMCO Assessment Camp', titleHi: 'मूल्यांकन शिविर में जाएं', descEn: 'Attend the district assessment camp organized by ALIMCO and District Administration.', descHi: 'एलिम्को और जिला प्रशासन द्वारा आयोजित मूल्यांकन शिविर में उपस्थित हों।' },
        { step: 2, titleEn: 'Device Distribution', titleHi: 'उपकरण वितरण', descEn: 'Receive customized assistive device fitted free of cost at the distribution camp.', descHi: 'वितरण शिविर में निशुल्क अनुकूलित उपकरण प्राप्त करें।' },
      ]),
      officialLink: 'https://myscheme.gov.in/schemes/rvy',
      departmentEn: 'Department of Social Justice and Empowerment',
      departmentHi: 'सामाजिक न्याय एवं अधिकारिता विभाग',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['senior-citizens'],
      titleEn: 'Pradhan Mantri Vaya Vandana Yojana (PMVVY)',
      titleHi: 'प्रधानमंत्री वय वंदना योजना (पीएमवीवीवाई)',
      descriptionEn: 'Government subsidized pension scheme for senior citizens operated exclusively by Life Insurance Corporation of India (LIC) providing assured returns.',
      descriptionHi: 'वरिष्ठ नागरिकों के लिए भारतीय जीवन बीमा निगम (एलआईसी) द्वारा संचालित सुनिश्चित मासिक रिटर्न वाली सरकारी पेंशन योजना।',
      benefitsEn: 'Guaranteed pension payout options (monthly, quarterly, half-yearly, or yearly) backed by sovereign guarantee for 10 years with loan facility up to 75% of purchase price.',
      benefitsHi: '10 वर्षों के लिए संप्रभु गारंटी द्वारा समर्थित सुनिश्चित पेंशन भुगतान, तथा खरीद मूल्य के 75% तक ऋण सुविधा।',
      benefitType: 'Social Security',
      benefitAmount: 'Up to ₹9,250 / Month Pension',
      eligibilityJson: JSON.stringify({
        minAge: 60,
        maxAge: 100,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Senior Citizen', 'All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card / PAN Card',
        'Age Verification Document',
        'Bank Account Details for Direct Credit of Pension',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Apply via LIC Portal or Branch', titleHi: 'एलआईसी पोर्टल या शाखा से आवेदन', descEn: 'Purchase offline at any LIC branch or online through licindia.in portal.', descHi: 'किसी भी एलआईसी शाखा में या ऑनलाइन licindia.in से योजना लें।' },
      ]),
      officialLink: 'https://licindia.in',
      departmentEn: 'Department of Financial Services, Ministry of Finance',
      departmentHi: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },

    // PERSONS WITH DISABILITIES (DIVYANGJAN)
    {
      categoryId: categoriesMap['divyangjan'],
      titleEn: 'ADIP Scheme - Assistance to Disabled Persons for Purchase/Fitting of Aids and Appliances',
      titleHi: 'एडीआईपी योजना - दिव्यांगजनों को सहायक उपकरणों की खरीद/फिटिंग हेतु सहायता',
      descriptionEn: 'Provides durable, sophisticated, and scientifically manufactured modern aids and assistive appliances to promote physical, social, and psychological rehabilitation of Divyangjan.',
      descriptionHi: 'दिव्यांगजनों के शारीरिक, सामाजिक एवं मनोवैज्ञानिक पुनर्वास हेतु आधुनिक, वैज्ञानिक रूप से निर्मित सहायक उपकरण निशुल्क या रियायती दर पर प्रदान करना।',
      benefitsEn: 'Full 100% grant for aids costing up to ₹15,000 for beneficiaries with monthly income up to ₹22,500. Motorized tricycles, smart canes, Daisy players, hearing aids, and prosthetics.',
      benefitsHi: '₹22,500 तक मासिक आय वाले लाभार्थियों को ₹15,000 तक के उपकरण 100% निशुल्क। मोटराइज्ड ट्राइसाइकिल, स्मार्ट केन, हियरिंग एड और कृत्रिम अंग।',
      benefitType: 'Social Security',
      benefitAmount: '100% Free Modern Assistive Appliances',
      eligibilityJson: JSON.stringify({
        minAge: 1,
        maxAge: 100,
        gender: 'All',
        maxIncome: 270000,
        states: ['All'],
        occupations: ['All'],
        categories: ['Divyangjan', 'All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'UDID Card (Unique Disability ID) or Disability Certificate (40% or more)',
        'Income Certificate (Monthly income under ₹22,500)',
        'Aadhaar Card',
        'Passport size photograph showing nature of disability',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Register on ALIMCO Portal', titleHi: 'एलिम्को पोर्टल पर पंजीकरण', descEn: 'Register on alimco.in or visit District Disability Rehabilitation Centre (DDRC).', descHi: 'alimco.in पर या जिला दिव्यांग पुनर्वास केंद्र (डीडीआरसी) में पंजीकरण करें।' },
        { step: 2, titleEn: 'Camp Verification', titleHi: 'शिविर सत्यापन', descEn: 'Undergo medical assessment in ALIMCO evaluation camp for prescription.', descHi: 'डॉक्टरों की टीम द्वारा आवश्यक उपकरण का परीक्षण व निर्धारण।' },
      ]),
      officialLink: 'https://adip.depwd.gov.in',
      departmentEn: 'Department of Empowerment of Persons with Disabilities, MSJE',
      departmentHi: 'दिव्यांगजन सशक्तिकरण विभाग, सामाजिक न्याय मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['divyangjan'],
      titleEn: 'Divyangjan Swavalamban Yojana (NDFDC Concessional Loans)',
      titleHi: 'दिव्यांगजन स्वावलंबन योजना (रियायती ऋण)',
      descriptionEn: 'Provides concessional financial assistance to Persons with Disabilities for starting self-employment ventures, business expansion, or pursuing higher technical education.',
      descriptionHi: 'दिव्यांगजनों को स्वरोजगार, लघु व्यवसाय शुरू करने या उच्च व्यावसायिक शिक्षा प्राप्त करने के लिए अत्यंत रियायती दरों पर ऋण सहायता।',
      benefitsEn: 'Loan amount up to ₹50 Lakh for self-employment projects and up to ₹20 Lakh for studies in India (up to ₹40 Lakh abroad) with subsidized interest rates of 5% - 8% p.a. Special 0.5% rebate for women with disabilities.',
      benefitsHi: 'स्वरोजगार के लिए ₹50 लाख तक तथा भारत में उच्च शिक्षा के लिए ₹20 लाख तक का ऋण मात्र 5% से 8% ब्याज दर पर। महिला दिव्यांगों को 0.5% की अतिरिक्त छूट।',
      benefitType: 'Financial',
      benefitAmount: 'Concessional Loans up to ₹50 Lakh',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 65,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Self-Employed', 'Student', 'Unemployed', 'All'],
        categories: ['Divyangjan', 'All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Disability Certificate / UDID (40% and above disability)',
        'Project report / business plan for self-employment',
        'Identity and Residence Proof (Aadhaar / Voter ID)',
        'Educational and training credentials',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Apply through State Channelising Agency (SCA)', titleHi: 'एससीए या बैंक के जरिए आवेदन', descEn: 'Submit project proposal to State Channelising Agency (SCA) or participating Regional Rural Bank.', descHi: 'राज्य चैनलाइजिंग एजेंसी या ग्रामीण बैंक में परियोजना रिपोर्ट जमा करें।' },
      ]),
      officialLink: 'https://nhfdc.nic.in',
      departmentEn: 'National Handicapped Finance and Development Corporation (NHFDC)',
      departmentHi: 'राष्ट्रीय दिव्यांगजन वित्त एवं विकास निगम',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['divyangjan'],
      titleEn: 'Unique Disability ID (UDID) Card Initiative',
      titleHi: 'विशिष्ट दिव्यांगता पहचान पत्र (यूडीआईडी) परियोजना',
      descriptionEn: 'Single nationwide smart ID card for Persons with Disabilities ensuring seamless access to travel concessions, pensions, scholarships, and all welfare benefits across India.',
      descriptionHi: 'दिव्यांगजनों के लिए देश भर में एक समान स्मार्ट पहचान पत्र, जो सभी सरकारी योजनाओं, रियायतों व पेंशन तक निर्बाध पहुंच सुनिश्चित करता है।',
      benefitsEn: 'Nationwide validity eliminating multiple certifications. Direct access to railway/bus fare concessions, priority queueing, and single-window scheme enrollment.',
      benefitsHi: 'देशभर में मान्य स्मार्ट कार्ड। रेल व बस किराए में छूट, प्राथमिकता सेवा और सभी सरकारी योजनाओं के लिए एकल खिड़की सुविधा।',
      benefitType: 'Social Security',
      benefitAmount: 'Pan-India Concessions & Verification',
      eligibilityJson: JSON.stringify({
        minAge: 0,
        maxAge: 100,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['All'],
        categories: ['Divyangjan', 'All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card',
        'Medical Assessment Report from District Medical Board',
        'Passport photograph showing disability condition',
        'Existing state disability certificate (if any)',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Register on UDID Portal', titleHi: 'यूडीआईडी पोर्टल पर पंजीकरण', descEn: 'Apply online on swavlambancard.gov.in and choose medical authority.', descHi: 'swavlambancard.gov.in पर ऑनलाइन आवेदन करें।' },
        { step: 2, titleEn: 'Medical Board Verification', titleHi: 'चिकित्सा बोर्ड सत्यापन', descEn: 'Visit the designated District Hospital for verification and receive digital/physical card.', descHi: 'सत्यापन के बाद डिजिटल ई-कार्ड और स्पीड पोस्ट द्वारा प्लास्टिक कार्ड प्राप्त करें।' },
      ]),
      officialLink: 'https://www.swavlambancard.gov.in',
      departmentEn: 'Department of Empowerment of Persons with Disabilities',
      departmentHi: 'दिव्यांगजन सशक्तिकरण विभाग',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },

    // EMPLOYMENT & SKILLS
    {
      categoryId: categoriesMap['employment'],
      titleEn: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
      titleHi: 'प्रधानमंत्री कौशल विकास योजना (पीएमकेवीवाई 4.0)',
      descriptionEn: 'Flagship skill certification scheme aimed at enabling youth to take up industry-relevant skill training that will help them secure a better livelihood.',
      descriptionHi: 'युवाओं को उद्योग-प्रासंगिक कौशल प्रशिक्षण लेने में सक्षम बनाकर बेहतर आजीविका हासिल करने में मदद करने वाली प्रमुख कौशल प्रमाणन योजना।',
      benefitsEn: '100% free skill training in modern disciplines (AI, Robotics, Drone Technology, Green Energy, Mechatronics), NSDC certification, assessment fee waiver, and placement support.',
      benefitsHi: 'आधुनिक क्षेत्रों (ड्रोन तकनीक, रोबोटिक्स, एआई, सौर ऊर्जा) में पूर्णतः निशुल्क प्रशिक्षण, एनएसडीसी प्रमाण पत्र और रोजगार सहायता।',
      benefitType: 'Livelihood',
      benefitAmount: '100% Free Training & Certification',
      eligibilityJson: JSON.stringify({
        minAge: 15,
        maxAge: 45,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Unemployed', 'Student', 'Daily Wage', 'All'],
        categories: ['All'],
        education: ['Below 10th', '10th Pass', '12th Pass', 'ITI/Diploma', 'Graduate', 'All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card',
        'Educational Marksheet (Class 10th / 12th / ITI)',
        'Active Bank Account (Aadhaar linked)',
        'Two Passport size photographs',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Find Skill India Centre', titleHi: 'कौशल केंद्र खोजें', descEn: 'Visit skillindia.gov.in or pmkvyofficial.org to search courses and approved centres.', descHi: 'skillindia.gov.in पर अपने नजदीकी प्रशिक्षण केंद्र और पाठ्यक्रम खोजें।' },
        { step: 2, titleEn: 'Enroll and Attend Classes', titleHi: 'नामांकन व प्रशिक्षण', descEn: 'Complete classroom & on-the-job training and clear the NSDC assessment.', descHi: 'कक्षा और व्यावहारिक प्रशिक्षण पूरा करें और परीक्षा उत्तीर्ण करें।' },
      ]),
      officialLink: 'https://www.pmkvyofficial.org',
      departmentEn: 'Ministry of Skill Development and Entrepreneurship',
      departmentHi: 'कौशल विकास एवं उद्यमिता मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['employment'],
      titleEn: 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
      titleHi: 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (मनरेगा)',
      descriptionEn: 'Guarantees at least 100 days of wage employment in a financial year to every rural household whose adult members volunteer to do unskilled manual work.',
      descriptionHi: 'प्रत्येक ग्रामीण परिवार को जिसके वयस्क सदस्य अकुशल शारीरिक श्रम करने के इच्छुक हैं, एक वित्तीय वर्ष में कम से कम 100 दिनों के रोजगार की कानूनी गारंटी।',
      benefitsEn: 'Guaranteed 100 days wage employment per rural household at statutory state wage rates directly deposited into the worker’s bank account, with unemployment allowance if work is not provided within 15 days.',
      benefitsHi: 'प्रति परिवार 100 दिनों का गारंटीकृत रोजगार। 15 दिनों में काम न मिलने पर बेरोजगारी भत्ता, और मजदूरी का सीधा बैंक खाते में भुगतान।',
      benefitType: 'Livelihood',
      benefitAmount: 'Statutory Daily Wage (100 Days Guarantee)',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 70,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Daily Wage', 'Agricultural Worker', 'Unemployed', 'Farmer'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card of all adult family members',
        'Proof of residence in rural Gram Panchayat',
        'Bank / Post Office Account details',
        'Passport sized photographs',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Apply for Job Card', titleHi: 'जॉब कार्ड हेतु आवेदन', descEn: 'Submit written or verbal application to local Gram Panchayat for Job Card.', descHi: 'अपनी ग्राम पंचायत में जॉब कार्ड के लिए मौखिक या लिखित आवेदन करें।' },
        { step: 2, titleEn: 'Receive Job Card & Demand Work', titleHi: 'काम की मांग करें', descEn: 'Job card is issued within 15 days. Submit written demand for work at Panchayat.', descHi: '15 दिनों में जॉब कार्ड प्राप्त करें और काम के लिए आवेदन दें।' },
      ]),
      officialLink: 'https://nrega.nic.in',
      departmentEn: 'Ministry of Rural Development',
      departmentHi: 'ग्रामीण विकास मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['employment'],
      titleEn: 'PM Street Vendor\'s AtmaNirbhar Nidhi (PM SVANidhi)',
      titleHi: 'पीएम स्ट्रीट वेंडर्स आत्मनिर्भर निधि (पीएम स्वनिधि)',
      descriptionEn: 'Micro-credit facility scheme for urban street vendors to resume their livelihoods with working capital loans and digital transaction cashbacks.',
      descriptionHi: 'रेहड़ी-पटरी और फेरी लगाने वाले स्ट्रीट वेंडरों को अपने आजीविका व्यवसाय को सशक्त करने हेतु सस्ता कार्यशील पूंजी ऋण।',
      benefitsEn: 'Initial working capital loan of ₹10,000. Upon prompt repayment, second tranche of ₹20,000 and third tranche of ₹50,000 at subsidized interest rates, plus up to ₹1,200 annual digital cashback.',
      benefitsHi: 'प्रथम चरण में ₹10,000 का ऋण। समय पर चुकाने पर ₹20,000 और फिर ₹50,000 का ऋण 7% ब्याज सब्सिडी और ₹1,200 वार्षिक डिजिटल कैशबैक के साथ।',
      benefitType: 'Financial',
      benefitAmount: '₹10,000 to ₹50,000 Collateral-free Loan',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 65,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Self-Employed', 'Daily Wage', 'All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card',
        'Vending Certificate / Identity Card issued by Urban Local Body (ULB) or Letter of Recommendation (LoR)',
        'Bank Account passbook linked to UPI',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Online Application on Portal', titleHi: 'पोर्टल पर आवेदन', descEn: 'Apply through pmsvanidhi.mohua.gov.in or via Common Service Centre (CSC).', descHi: 'pmsvanidhi.mohua.gov.in पर मोबाइल नंबर व आधार से आवेदन करें।' },
        { step: 2, titleEn: 'Bank Sanction', titleHi: 'ऋण स्वीकृति', descEn: 'Selected bank branch disburses the loan directly into the vendor bank account.', descHi: 'बैंक शाखा सीधे खाते में ऋण राशि हस्तांतरित करती है।' },
      ]),
      officialLink: 'https://pmsvanidhi.mohua.gov.in',
      departmentEn: 'Ministry of Housing and Urban Affairs',
      departmentHi: 'आवास और शहरी कार्य मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },

    // HOUSING
    {
      categoryId: categoriesMap['housing'],
      titleEn: 'Pradhan Mantri Awas Yojana - Urban (PMAY-U)',
      titleHi: 'प्रधानमंत्री आवास योजना - शहरी (पीएमएवाई-यू)',
      descriptionEn: 'Provides all-weather pucca houses to eligible urban families belonging to EWS, LIG, and MIG categories across statutory towns in India.',
      descriptionHi: 'देश भर के सांविधिक कस्बों में ईडब्ल्यूएस, एलआईजी और एमआईजी श्रेणियों के पात्र शहरी परिवारों को पक्के मकान उपलब्ध कराना।',
      benefitsEn: 'Up to ₹2.67 Lakh interest subsidy on home loans under Credit Linked Subsidy Scheme (CLSS), or direct central assistance of ₹1.5 Lakh for beneficiary-led individual construction.',
      benefitsHi: 'होम लोन पर ₹2.67 लाख तक की ब्याज सब्सिडी, अथवा स्वयं मकान निर्माण हेतु ₹1.5 लाख की सीधी केंद्रीय सहायता।',
      benefitType: 'Housing',
      benefitAmount: 'Up to ₹2.67 Lakh Subsidy',
      eligibilityJson: JSON.stringify({
        minAge: 21,
        maxAge: 70,
        gender: 'All',
        maxIncome: 600000,
        states: ['All'],
        occupations: ['All'],
        categories: ['All', 'EWS', 'General', 'OBC', 'SC', 'ST'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card of all family members',
        'Income Certificate / Salary Slip / ITR (Income below ₹3 Lakh for EWS, below ₹6 Lakh for LIG)',
        'Affidavit declaring no pucca house owned anywhere in India',
        'Land Ownership / Mutation papers (for construction component)',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Apply Online', titleHi: 'ऑनलाइन आवेदन', descEn: 'Apply on pmaymis.gov.in under Citizen Assessment or through local municipality / CSC.', descHi: 'pmaymis.gov.in पर जाएं और "Citizen Assessment" पर क्लिक करके फॉर्म भरें।' },
        { step: 2, titleEn: 'Geo-Tagging & Verification', titleHi: 'जियो-टैगिंग व सत्यापन', descEn: 'Municipal authorities inspect site and geo-tag before stage-wise subsidy release.', descHi: 'नगर पालिका द्वारा सत्यापन और किस्तों में सब्सिडी का सीधे खाते में हस्तांतरण।' },
      ]),
      officialLink: 'https://pmaymis.gov.in',
      departmentEn: 'Ministry of Housing and Urban Affairs',
      departmentHi: 'आवास और शहरी कार्य मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['housing'],
      titleEn: 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G)',
      titleHi: 'प्रधानमंत्री आवास योजना - ग्रामीण (पीएमएवाई-जी)',
      descriptionEn: 'Provides financial assistance to rural families living in kutcha or dilapidated houses to construct disaster-resilient pucca houses with basic amenities.',
      descriptionHi: 'कच्चे या जीर्ण-शीर्ण मकानों में रहने वाले ग्रामीण परिवारों को बुनियादी सुविधाओं से युक्त पक्के मकान बनाने के लिए वित्तीय सहायता।',
      benefitsEn: 'Unit assistance of ₹1,20,000 in plains and ₹1,30,000 in hilly/difficult areas, plus ₹12,000 for toilet construction under Swachh Bharat Mission and 90 days unskilled labor under MGNREGA.',
      benefitsHi: 'मैदानी क्षेत्रों में ₹1,20,000 और पहाड़ी/कठिन क्षेत्रों में ₹1,30,000 की सहायता, साथ ही शौचालय हेतु ₹12,000 और मनरेगा मजदूरी।',
      benefitType: 'Housing',
      benefitAmount: '₹1,20,000 - ₹1,30,000 Grant',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 75,
        gender: 'All',
        maxIncome: 180000,
        states: ['All'],
        occupations: ['Farmer', 'Agricultural Worker', 'Daily Wage', 'All'],
        categories: ['All', 'SC', 'ST', 'Minority', 'OBC', 'General'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card',
        'SECC-2011 / Awas+ Household Verification ID',
        'Active Bank Account details (DBT enabled)',
        'Land possession certificate / Gram Sabha resolution',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Selection via Gram Sabha', titleHi: 'ग्राम सभा द्वारा चयन', descEn: 'Beneficiaries are identified from Awas+ priority list approved by Gram Sabha.', descHi: 'आवास प्लस सूची से ग्राम सभा द्वारा पात्र परिवारों का चयन किया जाता है।' },
        { step: 2, titleEn: 'Mobile App Geo-tagging', titleHi: 'आवास ऐप जियो-टैगिंग', descEn: 'Inspection at foundation, lintel, and roof stages via AwaasApp releases installments.', descHi: 'निर्माण के प्रत्येक स्तर पर जियो-टैगिंग के बाद सीधे खाते में किस्तें आती हैं।' },
      ]),
      officialLink: 'https://pmayg.nic.in',
      departmentEn: 'Ministry of Rural Development',
      departmentHi: 'ग्रामीण विकास मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },

    // HEALTH & WELLNESS
    {
      categoryId: categoriesMap['health'],
      titleEn: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)',
      titleHi: 'आयुष्मान भारत - प्रधानमंत्री जन आरोग्य योजना (एबी-पीएमजेएवाई)',
      descriptionEn: 'The world\'s largest government-funded health assurance scheme providing comprehensive secondary and tertiary hospitalization care without out-of-pocket costs.',
      descriptionHi: 'विश्व की सबसे बड़ी सरकारी स्वास्थ्य आश्वासन योजना, जो पात्र परिवारों को द्वितीयक और तृतीयक अस्पताल भर्ती के लिए निशुल्क कवरेज प्रदान करती है।',
      benefitsEn: 'Cashless and paperless health insurance cover of ₹5,00,000 per family per year for secondary and tertiary care hospitalization across all empaneled public and private hospitals across India.',
      benefitsHi: 'प्रति परिवार प्रति वर्ष ₹5,00,000 का पूर्णतः निशुल्क और कैशलेस स्वास्थ्य बीमा कवर। देश भर के सभी सूचीबद्ध सरकारी व निजी अस्पतालों में मान्य।',
      benefitType: 'Health',
      benefitAmount: '₹5,00,000 / Year Cashless Cover',
      eligibilityJson: JSON.stringify({
        minAge: 0,
        maxAge: 100,
        gender: 'All',
        maxIncome: 250000,
        states: ['All'],
        occupations: ['All'],
        categories: ['All', 'SC', 'ST', 'OBC', 'General', 'EWS'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card (Mandatory for beneficiary verification)',
        'Ration Card / PM-JAY Family ID / SECC identification letter',
        'Mobile number linked to Aadhaar',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Check Eligibility Online', titleHi: 'पात्रता जांचें', descEn: 'Visit beneficiary.nha.gov.in or download the Ayushman App to verify your family name.', descHi: 'beneficiary.nha.gov.in पर मोबाइल नंबर और आधार से परिवार की पात्रता खोजें।' },
        { step: 2, titleEn: 'Complete eKYC & Download Ayushman Card', titleHi: 'ई-केवाईसी और कार्ड डाउनलोड', descEn: 'Complete Aadhaar OTP or Face eKYC and download the golden Ayushman Card instantly.', descHi: 'ओटीपी या चेहरे के प्रमाणीकरण से ई-केवाईसी पूरा करें और तुरंत गोल्डन कार्ड डाउनलोड करें।' },
      ]),
      officialLink: 'https://beneficiary.nha.gov.in',
      departmentEn: 'National Health Authority (NHA), Ministry of Health and Family Welfare',
      departmentHi: 'राष्ट्रीय स्वास्थ्य प्राधिकरण (एनएचए), स्वास्थ्य एवं परिवार कल्याण मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['health'],
      titleEn: 'Pradhan Mantri Bhartiya Janaushadhi Pariyojana (PMBJP)',
      titleHi: 'प्रधानमंत्री भारतीय जनऔषधि परियोजना (पीएमबीजेपी)',
      descriptionEn: 'Campaign launched by the Department of Pharmaceuticals to provide quality generic medicines at affordable prices to all through dedicated Jan Aushadhi Kendras.',
      descriptionHi: 'विशेष जनऔषधि केंद्रों के माध्यम से सभी नागरिकों को सस्ती कीमतों पर गुणवत्तापूर्ण जेनेरिक दवाएं उपलब्ध कराने की राष्ट्रव्यापी परियोजना।',
      benefitsEn: 'Quality medicines sold at 50% to 90% cheaper prices compared to branded medicines in open market. Over 1,900 generic medicines and 300 surgical devices available.',
      benefitsHi: 'खुले बाजार की ब्रांडेड दवाओं की तुलना में 50% से 90% कम कीमत पर उच्च गुणवत्ता वाली जेनेरिक दवाएं व सर्जिकल उपकरण उपलब्ध।',
      benefitType: 'Health',
      benefitAmount: '50% - 90% Savings on Medicines',
      eligibilityJson: JSON.stringify({
        minAge: 0,
        maxAge: 100,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Doctor Prescription (for prescription-only medicines)',
        'No income or category restriction; open for all Indian citizens',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Locate Jan Aushadhi Kendra', titleHi: 'जन औषधि केंद्र खोजें', descEn: 'Use Janaushadhi Sugam Mobile App or janaushadhi.gov.in to find nearest store.', descHi: 'जनऔषधि सुगम ऐप पर अपने निकटतम केंद्र और दवा की उपलब्धता देखें।' },
        { step: 2, titleEn: 'Purchase at Subsidized Rates', titleHi: 'रियायती दर पर दवा खरीदें', descEn: 'Show prescription at any of the 10,000+ Kendras and buy medicines at wholesale prices.', descHi: 'पर्चा दिखाकर रियायती दर पर दवा प्राप्त करें।' },
      ]),
      officialLink: 'https://janaushadhi.gov.in',
      departmentEn: 'Pharmaceuticals & Medical Devices Bureau of India (PMBI)',
      departmentHi: 'भारतीय फार्मास्यूटिकल्स एवं मेडिकल डिवाइसेज ब्यूरो',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['health'],
      titleEn: 'Mission Indradhanush (Universal Immunization Programme)',
      titleHi: 'मिशन इंद्रधनुष (सार्वभौमिक टीकाकरण कार्यक्रम)',
      descriptionEn: 'Provides life-saving free vaccination against 12 vaccine-preventable diseases to all unvaccinated or partially vaccinated pregnant women and children under age 2.',
      descriptionHi: 'गर्भवती महिलाओं और 2 वर्ष तक के बच्चों को 12 जानलेवा बीमारियों से बचाने के लिए निशुल्क सार्वभौमिक टीकाकरण सुरक्षा।',
      benefitsEn: '100% free immunization covering Diphtheria, Pertussis, Tetanus, Polio, Measles, Rubella, severe childhood Tuberculosis, Hepatitis B, Meningitis, Pneumonia, and Rotavirus diarrhea.',
      benefitsHi: '12 जानलेवा बीमारियों के खिलाफ 100% निशुल्क टीकाकरण, सुरक्षित मातृत्व और शिशु स्वास्थ्य सुरक्षा।',
      benefitType: 'Health',
      benefitAmount: '100% Free Vaccination',
      eligibilityJson: JSON.stringify({
        minAge: 0,
        maxAge: 5,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Mother-Child Protection (MCP) Card / RCH Portal Registration',
        'Aadhaar Card of Parents (Optional, no child denied for lack of ID)',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Visit Health Centre', titleHi: 'स्वास्थ्य केंद्र जाएं', descEn: 'Visit any Primary Health Centre (PHC), Community Health Centre (CHC), or Anganwadi.', descHi: 'नजदीकी प्राथमिक स्वास्थ्य केंद्र या आंगनवाड़ी केंद्र पर संपर्क करें।' },
        { step: 2, titleEn: 'Receive Vaccination & U-WIN Record', titleHi: 'टीकाकरण व यू-विन रिकॉर्ड', descEn: 'Get vaccinated and view digital certificate on the U-WIN platform (uwin.mohfw.gov.in).', descHi: 'टीका लगवाएं और यू-विन पोर्टल पर डिजिटल प्रमाण पत्र देखें।' },
      ]),
      officialLink: 'https://www.mohfw.gov.in',
      departmentEn: 'Ministry of Health and Family Welfare',
      departmentHi: 'स्वास्थ्य एवं परिवार कल्याण मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['farmers'],
      titleEn: 'Kisan Credit Card (KCC) Scheme',
      titleHi: 'किसान क्रेडिट कार्ड (केसीसी) योजना',
      descriptionEn: 'Provides timely and affordable institutional credit to farmers for agricultural inputs, cultivating expenses, crop harvesting, and post-harvest maintenance at subsidized interest rates.',
      descriptionHi: 'किसानों को खेती की जरूरतों, फसल बुवाई और कृषि उपकरणों के लिए रियायती ब्याज दर पर समय पर संस्थागत बैंक ऋण उपलब्ध कराना।',
      benefitsEn: 'Credit limit up to ₹3,00,000 at effective interest rate of 4% per annum (with 3% prompt repayment incentive). Collateral-free loan up to ₹1,60,000.',
      benefitsHi: 'समय पर भुगतान करने पर मात्र 4% वार्षिक रियायती ब्याज दर पर ₹3 लाख तक का कृषि ऋण। ₹1.60 लाख तक बिना किसी गारंटी के ऋण।',
      benefitType: 'Financial',
      benefitAmount: '₹3,00,000 Credit at 4% Interest',
      eligibilityJson: JSON.stringify({
        minAge: 18,
        maxAge: 75,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['Farmer', 'Agricultural Worker', 'Self-Employed'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card and Land ownership record (Khatauni / Khasra)',
        'Passport sized photographs',
        'Declaration of crops sown in current agricultural season',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Submit KCC Form at Bank', titleHi: 'बैंक में फॉर्म जमा करें', descEn: 'Fill 1-page simplified KCC form at any commercial or cooperative bank.', descHi: 'किसी भी वाणिज्यिक या सहकारी बैंक शाखा में सरल केसीसी फॉर्म भरें।' },
        { step: 2, titleEn: 'Card Issuance within 14 Days', titleHi: '14 दिनों में कार्ड जारी', descEn: 'Bank issues RuPay KCC card with credit limit approved within 14 days.', descHi: 'बैंक 14 दिनों के भीतर सीमा स्वीकृत कर रूपे केसीसी कार्ड जारी करता है।' },
      ]),
      officialLink: 'https://pmkisan.gov.in',
      departmentEn: 'Department of Agriculture & Farmers Welfare',
      departmentHi: 'कृषि एवं किसान कल्याण विभाग',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['women'],
      titleEn: 'Mahila Samman Savings Certificate (MSSC)',
      titleHi: 'महिला सम्मान बचत प्रमाण पत्र योजना (MSSC)',
      descriptionEn: 'A high-interest sovereign savings scheme launched by the Ministry of Finance to promote financial inclusion, security, and wealth accumulation for women and girl children.',
      descriptionHi: 'महिलाओं और बालिकाओं के वित्तीय सशक्तिकरण एवं सुरक्षित बचत को बढ़ावा देने के लिए वित्त मंत्रालय द्वारा शुरू की गई उच्च ब्याज दर वाली योजना।',
      benefitsEn: 'Guaranteed attractive interest rate of 7.5% per annum compounded quarterly on deposits from ₹1,000 up to ₹2,00,000 for a fixed 2-year tenure. Partial withdrawal up to 40% allowed after 1 year.',
      benefitsHi: '2 वर्ष की अवधि के लिए 7.5% वार्षिक निश्चित ब्याज दर (त्रैमासिक चक्रवृद्धि)। ₹1,000 से ₹2,00,000 तक जमा राशि। 1 वर्ष बाद 40% तक निकासी की सुविधा।',
      benefitType: 'Financial',
      benefitAmount: '7.5% Guaranteed Sovereign Interest',
      eligibilityJson: JSON.stringify({
        minAge: 0,
        maxAge: 100,
        gender: 'Female',
        maxIncome: null,
        states: ['All'],
        occupations: ['All'],
        categories: ['All'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Aadhaar Card of the woman or girl beneficiary',
        'PAN Card',
        'Passport size photograph & KYC Form',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Visit Post Office or Bank', titleHi: 'डाकघर या बैंक जाएं', descEn: 'Visit any India Post office or authorized public sector bank branch.', descHi: 'निकटतम भारतीय डाकघर या अधिकृत बैंक शाखा में जाएं।' },
        { step: 2, titleEn: 'Open MSSC Account', titleHi: 'खाता खोलें', descEn: 'Fill Account Opening Form-1 and deposit funds to receive the official certificate.', descHi: 'फॉर्म भरकर राशि जमा करें और प्रमाण पत्र प्राप्त करें।' },
      ]),
      officialLink: 'https://www.indiapost.gov.in',
      departmentEn: 'Department of Economic Affairs, Ministry of Finance',
      departmentHi: 'आर्थिक कार्य विभाग, वित्त मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
    {
      categoryId: categoriesMap['divyangjan'],
      titleEn: 'Deendayal Disabled Rehabilitation Scheme (DDRS)',
      titleHi: 'दीनदयाल दिव्यांग पुनर्वास योजना (डीडीआरएस)',
      descriptionEn: 'Provides financial grants and rehabilitation support to non-governmental organizations to deliver vocational training, special education, and early intervention to persons with disabilities.',
      descriptionHi: 'दिव्यांगजनों को विशेष शिक्षा, व्यावसायिक प्रशिक्षण और पुनर्वास सेवाएं प्रदान करने वाली संस्थाओं और केंद्रों को सहायता देने की केंद्रीय योजना।',
      benefitsEn: 'Free special education, community-based rehabilitation, vocational training, assistive therapies, and stipend support for students with intellectual and physical disabilities.',
      benefitsHi: 'निशुल्क विशेष शिक्षा, सामुदायिक पुनर्वास, व्यावसायिक कौशल प्रशिक्षण, सहायक थेरेपी और छात्रवृत्ति सहायता।',
      benefitType: 'Social Security',
      benefitAmount: '100% Free Special Education & Therapy',
      eligibilityJson: JSON.stringify({
        minAge: 0,
        maxAge: 65,
        gender: 'All',
        maxIncome: null,
        states: ['All'],
        occupations: ['All'],
        categories: ['All', 'Divyangjan'],
        education: ['All'],
      }),
      documentsRequired: JSON.stringify([
        'Unique Disability ID (UDID) Card / Disability Certificate (40% or more disability)',
        'Aadhaar Card of Beneficiary',
        'Income Certificate of Parents/Guardian',
      ]),
      applicationProcess: JSON.stringify([
        { step: 1, titleEn: 'Apply via DDRS NGO Portal', titleHi: 'डीडीआरएस पोर्टल पर आवेदन', descEn: 'Enroll at nearest DDRS special school or apply on ngograntsmis.gov.in.', descHi: 'निकटतम विशेष विद्यालय केंद्र में संपर्क करें या ऑनलाइन पोर्टल पर नाम दर्ज करें।' },
        { step: 2, titleEn: 'Avail Free Rehabilitation Support', titleHi: 'निशुल्क सहायता प्राप्त करें', descEn: 'Get admitted for skill training, specialized therapy, and assistive equipment.', descHi: 'कौशल प्रशिक्षण व सहायक उपकरणों का निशुल्क लाभ लें।' },
      ]),
      officialLink: 'https://disabilityaffairs.gov.in',
      departmentEn: 'Department of Empowerment of Persons with Disabilities, MSJE',
      departmentHi: 'दिव्यांगजन सशक्तिकरण विभाग, सामाजिक न्याय एवं अधिकारिता मंत्रालय',
      level: 'Central',
      status: 'PUBLISHED',
      createdByAdminId: admin.id,
    },
  ];

  for (const s of schemesData) {
    const created = await prisma.scheme.create({ data: s });
    // Add sample bookmark & application for the demo user
    if (s.titleEn.includes('College and University Students')) {
      await prisma.bookmark.create({
        data: {
          userId: demoUser.id,
          schemeId: created.id,
        },
      });
      await prisma.applicationTracker.create({
        data: {
          userId: demoUser.id,
          schemeId: created.id,
          status: 'APPLIED',
          notes: 'Submitted application on National Scholarship Portal with application ID NSP/2026/98214.',
        },
      });
    }
  }
  console.log(`✅ Seeded ${schemesData.length} authentic central government schemes`);

  // 4. Create Sample Notifications for Demo User
  await prisma.notification.createMany({
    data: [
      {
        userId: demoUser.id,
        type: 'SCHEME_MATCH',
        titleEn: 'New Scheme Matched Your Profile!',
        titleHi: 'आपकी प्रोफ़ाइल से नई योजना मेल खाती है!',
        messageEn: 'Central Sector Scheme of Scholarships matches 98% of your criteria (Student, Age 24, Income < ₹4.5 Lakh).',
        messageHi: 'कॉलेज और विश्वविद्यालय छात्रवृत्ति योजना आपकी प्रोफ़ाइल से 98% मेल खाती है।',
        link: '/schemes',
        read: false,
      },
      {
        userId: demoUser.id,
        type: 'DEADLINE',
        titleEn: 'Application Deadline Approaching',
        titleHi: 'आवेदन की अंतिम तिथि निकट है',
        messageEn: 'Remember to verify your application documents before the upcoming NSP verification cycle.',
        messageHi: 'एनएसपी सत्यापन चक्र से पहले अपने आवेदन दस्तावेजों का सत्यापन कराना न भूलें।',
        link: '/dashboard',
        read: false,
      },
    ],
  });
  console.log('✅ Created Initial Notifications');

  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error during seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
